# Generated by Django 4.2 on 2023-04-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, null=True, verbose_name='Apellido')),
                ('identificacion', models.IntegerField(null=True, verbose_name='Identificacion')),
                ('hora', models.IntegerField(null=True, verbose_name='Hora')),
                ('fecha', models.DateField(max_length=10, null=True, verbose_name='Fecha')),
                ('medico', models.CharField(max_length=100, null=True, verbose_name='Medico')),
            ],
        ),
    ]
