# Generated by Django 4.2 on 2023-05-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='hora',
            field=models.TimeField(max_length=100, null=True, verbose_name='Hora'),
        ),
    ]
